name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        laravel: ['10', '11']
        exclude:
          # Laravel 11 requires PHP 8.2+
          - php: '8.1'
            laravel: '11'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-

      - name: Install dependencies
        run: |
          if [ "${{ matrix.laravel }}" = "10" ]; then
            composer require "laravel/framework:^10.0" "orchestra/testbench:^8.0" --no-interaction --no-update --dev
          else
            composer require "laravel/framework:^11.0" "orchestra/testbench:^9.0" --no-interaction --no-update --dev
          fi
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --no-coverage

  coverage:
    runs-on: ubuntu-latest
    
    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-8.2-laravel-11-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-8.2-laravel-11-composer-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^11.0" "orchestra/testbench:^9.0" --no-interaction --no-update --dev
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests with coverage
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false